### ISSUE TITLE
Dark mode: Menu tweaks

### ISSUE THREAD

**Issue by weekbeforenext** [a11ytalks/a11ytalks-drupal#1]
- The tagline is a lighter font color.
- The icons are missing.
<img width="672" alt="missing_icons_and_font_color" src="https://github.com/a11ytalks/a11ytalks-drupal/assets/1434979/a3e6ee33-b784-487d-8f42-d55b9e950ce7">

**Comment by mark-casias** [comment]
Whoops.. Forgot to add the contact block to the sidebar.. Updated.

Also lightened the site slogan color to match the live site.

**Comment by mark-casias** [comment]
@weekbeforenext can we close this?

**Comment by weekbeforenext** [comment]
Yep.
