### ISSUE TITLE
On the home page, all social icons have the same alt of Twitter

### ISSUE THREAD

**Issue by Menelion** [a11ytalks/a11ytalks-drupal#12]
On the main page of https://a11ytalks.com/ after the navigation region there are four social network links with icons (YouTube, Twitter etc.). All of them expose the same alt text for screen readers: `Twitter`.  
I'd be glad to help and send a quick PR for this, but I couldn't wrap my head around this… interesting setup quickly enough and figure out where those links are formed and where those alt texts for icons can be found. I'm not really experienced in Drupal, although PHP is my main language.

**Comment by mark-casias** [comment]
This has been resolved with the last push.
